"""added field to user model: about_me, last_visited.

Revision ID: 238e8fa219ff
Revises: d05300d54f46
Create Date: 2019-03-20 13:19:59.999519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238e8fa219ff'
down_revision = 'd05300d54f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_visited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_visited')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
